#      ███████╗███████╗██╗  ██╗██████╗  ██████╗
#      ╚══███╔╝██╔════╝██║  ██║██╔══██╗██╔════╝
#        ███╔╝ ███████╗███████║██████╔╝██║
#       ███╔╝  ╚════██║██╔══██║██╔══██╗██║
#      ███████╗███████║██║  ██║██║  ██║╚██████╗
#     ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝
#
#▁ ▂ ▄ ▅ ▆ ▇ █ File generated by ansible █ ▇ ▆ ▅ ▄ ▂ ▁

export PATH=$HOME/.config/scripts:$HOME/.pyenv/bin/:$PATH
export ZSH="$HOME/.oh-my-zsh"
export CONFIG="$HOME/.config"
export EDITOR="/opt/homebrew/bin/nvim"

plugins=(
  colored-man-pages
  command-not-found
  ripgrep
  fd
  mosh
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-interactive-cd
  zsh-navigation-tools
  zoxide
  starship
)

source $ZSH/oh-my-zsh.sh
source $HOME/.aliases
#This is a hack to get zellij completions working,
#I am still trying to figure out what compinit does not pick it up
#I source is directly for now because I want the aliases to be available
source $CONFIG/completions/_zellij >> /dev/null 2>&1
