---

dev::
  hosts:
  vars:
    no_log: false
    host_package: full

raspberry:
  hosts:
    100.76.161.87:
    100.127.144.135:
    100.79.250.120:
    100.109.50.19:
    100.125.136.76:
  vars:
    no_log: false
    host_package: default
