---
- name: Add asciiquarium ppa
  apt_repository:
    validate_certs: no
    repo: "ppa:ytvwld/asciiquarium"
    state: present
  become: true
- name: Install asciiquarium
  apt:
    name: asciiquarium
    state: latest
    update_cache: yes
  become: true
