 - name: Set SSH Key for Ansible
   authorized_key:
      user: "agluck"
      state: present
      key: "{{ key.name }}"
   loop: "{{ ssh_keys }}"
   loop_control:
     loop_var: "key"
   when: local | bool
