---
  - name: Debug message
    ansible.builtin.debug:
      msg: "{{ [ansible_architecture] }}"
  - name: Gathering Installed Package
    package_facts:
  - name: "Update APT Repos and Upgrade APT Packages"
    ansible.builtin.apt:
      update_cache: true
      upgrade: "yes"
      autoremove: true
      autoclean: true
    become: true
  - name: "Install base packages"
    ansible.builtin.apt:
      name:
        - jq
        - wget
        - cmake
        - pkg-config
        - libtool
        - unzip
        - exa
        - curl
        - ripgrep
        - mosh
        - bat
        - tmux
        - btop
        - zoxide
        - ufw
      state: latest
    become: true
  - name: Upload global ansible configuration
    when: host_package == "full"
    copy:
      src: .ansible.cfg
      dest: "{{ ansible_user_dir }}/.ansible.cfg"
      follow: true
  - name: Configure firewall for mosh
    ufw:
      rule: allow
      proto: udp
      port: 60000:60030
    become: true
