---
## DEPS
- name: Install dev_tools dependecies
  apt:
    pkg:
      - make
      - gcc
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
    state: latest
    update_cache: true
  become: true

## PYENV/PYTHON
- name: Install pyenv
  script:
    cmd: pyenv-installer
    creates: "{{ ansible_user_dir }}/.pyenv/"

## GOLANG
- name: Install golang
  apt:
    pkg:
      - golang-go
    state: latest
  become: true

## JS/TS
- name: Install volta
  script:
    cmd: volta-installer
    creates: "{{ ansible_user_dir }}/.volta/"

- name: Install Node
  command:
    cmd: "{{ ansible_user_dir }}/.volta/bin/volta install node"
    creates: "{{ ansible_user_dir }}/.volta/bin/node"


## RUST
- name: Install rust/cargo
  script:
    cmd: sh.rustup.rs -y
    creates: "{{ ansible_user_dir }}/.cargo/"

##k Common dev_tools
- name: Install sshfs
  apt:
    pkg:
      - sshfs
    state: latest
  become: true

