ssh_keys:
  - name: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMbu0R7cGNnq7xmHwoBtVMGTaAN2ijpecyyGDA4HS4Rb Ansible_Key
  - name: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpso6EJmgJLnJmCRCKs5HiAC0blLMiKVyGnhI3/Gktj Mobile Shell
  - name: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILtnMgEAFNMutvv1/FnR6s4njCGB2RdXt3fD8QbCRLww Andrews MBP
