# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Variables Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/mocha.conf

# Variables wiki https://wiki.hyprland.org/Configuring/Variables/ #
# https://wiki.hyprland.org/Configuring/Variables/#general
general {

    gaps_in = 3
    gaps_out = 5
    border_size = 3
    col.active_border = rgba(a6e3a1ff) rgba(94e2d5ff) rgba(89b4faff) 45deg
    col.inactive_border = $blue
    layout = dwindle # master|dwindle

    # https://wiki.hyprland.org/Configuring/Variables/#snap
    snap {
    	enabled = true
    }

}

# https://wiki.hyprland.org/Configuring/Variables/#group
group {
	col.border_active = $green
	col.border_inactive = $green
	col.border_locked_active = $green
	col.border_locked_inactive = $blue

    # https://wiki.hyprland.org/Configuring/Variables/#groupbar
	groupbar {
		font_family = "Fira Sans"
		text_color = $text
		col.active = $base
		col.inactive = $green
		col.locked_active = $green
		col.locked_inactive = $blue
	}
}
# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    font_family = "Fira Sans"
    splash_font_family = "Fira Sans"
    disable_hyprland_logo = true
    col.splash = $green
    background_color = $blue
    enable_swallow = true
    swallow_regex = ^(cachy-browser|firefox|nautilus|nemo|thunar|btrfs-assistant.)$
    focus_on_activate = true
    vrr = 2
}

# https://wiki.hyprland.org/Configuring/Variables/#render
render {
   direct_scanout = true
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    special_scale_factor = 0.8
    pseudotile = true
    preserve_split = true
}

cursor {
    no_warps = false
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
    special_scale_factor = 0.8
}

# See https://wiki.hyprland.org/Configuring/Scrolling-Layout/ for more
scrolling {
    column_width             = 0.75
    follow_focus             = true
    fullscreen_on_one_column = true
}
