---
- name: "Neovim | Install"
  apt:
    name: neovim
    state: present
  become: true

- name: "Establish Config folder"
  file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Copy init.lua"
  copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
    src: "init.lua"
    mode: 0644

- name: "Copy main modules"
  copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/lua"
    src: "lua/"
    mode: 0644

- name: "Copy after files"
  copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/after"
    src: "after/"
    mode: 0644
